#!/bin/bash

PKGBUILD=$1
USER=$2
PASSWD=$3
PKGBUILDS=$(find $1 -iname "PKGBUILD")

# Pushs the tarball to Archlinux
# Args:
#  - $1: source tarball path
push() {
  echo ";"
}

# Generates the source tarball which will be uploaded to
# Archlinux.
generate() {
  echo ";"
}

# Checks the validity of the .pkgspec file.
validate_pkgspec() {

}

unset pkgname
for pkg in $PKGBUILDS; do
  spec="$(dirname "$i")/.pkgspec"
  source $pkg

done
