#!/bin/bash
#
# github-aur, maintain AUR packages with Github and Travis CI
# 
# Copyright (C) 2013, Jens Nazarenus <jems@0x6a.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

declare -r myname='travis-prepare'
declare -r myversion='1.0.0'

usage() {
  echo -e  "Usage: $myname"
  echo -en "Prepare the filesystem for github-aur and travis"
  echo -e  "Report bugs to: jens@0x6a.de"
  echo -e  "$myname home page: <http://github.com/jens-na/$myname>"
}

version() {
  printf "%s %s\n" "$myname" "$myversion"
  echo "Copyright (C) 2013 Jens Nazarenus <jens@0x6a.de>"
}

# update git submodules
git submodule update --init --recursive

# update dependencies
sudo apt-get install -qq libarchive-dev

# download pacman and extract it
mkdir -p pacman-install
wget "https://www.archlinux.de/?page=GetFileFromMirror;file=core%2Fos%2Fx86_64%2Fpacman-4.1.2-1-x86_64.pkg.tar.xz" -O pacman.pkg.tar.gz
tar -xvf pacman.pkg.tar.gz -C pacman-install
sudo ldconfig ./pacman-install/usr/lib

# update mirrorlist
mkdir -p ./pacman-install/etc/pacman.d/
echo "Server = http://ftp.tu-chemnitz.de/pub/linux/archlinux/\$repo/os/\$arch" >> ./pacman-install/etc/pacman.d/mirrorlist

sudo ./pacman-install/usr/bin/pacman --root ./pacman-install -Sy
sudo ./pacman-install/usr/bin/pacman --root ./pacman-install -Ss
