#!/bin/bash
#
# github-aur, maintain AUR packages with Github and Travis CI
# 
# Copyright (C) 2013, Jens Nazarenus <jems@0x6a.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

declare -r myname='travis-prepare'
declare -r myversion='1.0.0'

usage() {
  echo -e  "Usage: $myname"
  echo -en "Prepare the filesystem for github-aur and travis"
  echo -e  "Report bugs to: jens@0x6a.de"
  echo -e  "$myname home page: <http://github.com/jens-na/$myname>"
}

version() {
  printf "%s %s\n" "$myname" "$myversion"
  echo "Copyright (C) 2013 Jens Nazarenus <jens@0x6a.de>"
}

cd github-aur/pacman/
./autogen.sh
./configure
cd scripts/
make
find
