#!/bin/bash
#
# github-aur, maintain AUR packages with Github and Travis CI
# 
# Copyright (C) 2013, Jens Nazarenus <jems@0x6a.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

declare -r myname='travis-prepare'
declare -r myversion='1.0.0'

usage() {
  echo -e  "Usage: $myname"
  echo -en "Prepare the filesystem for github-aur and travis"
  echo -e  "Report bugs to: jens@0x6a.de"
  echo -e  "$myname home page: <http://github.com/jens-na/$myname>"
}

version() {
  printf "%s %s\n" "$myname" "$myversion"
  echo "Copyright (C) 2013 Jens Nazarenus <jens@0x6a.de>"
}

git submodule update --init --recursive

# libarchive-dev needs to be installed to build pacman
sudo apt-get install -qq libarchive-dev asciidoc

#
# make and prepare pacman
# 
cd github-aur/pacman/
./autogen.sh
./configure
make
sudo make install
#sudo mkdir -p /var/lib/pacman/local
#sudo mkdir -p /var/lib/pacman/sync
sudo ldconfig

sudo echo "Server = http://ftp.tu-chemnitz.de/pub/linux/archlinux/\$repo/os/\$arch" >> /usr/local/etc/pacman.d/mirrorlist

find /usr/etc

cat /usr/local/etc/pacman.conf
cat /usr/local/etc/pacman.d/mirrorlist
#
# test pacman 
# 
sudo pacman -S
pacman -Ss

#export MAKEPKG="`pwd`/github-aur/pacman/scripts/makepkg"
#export MAKEPKG_CFG="`pwd`/github-aur/etc/makepkg.conf"

#echo $MAKEPKG
#echo $MAKEPKG_CFG
